function calcular (valor) {
    if (valor === 0) {
        throw new Error('NÃ£o pode ser 0')
    }
    return valor / 2;
}

try {
    const res = calcular(543)
    console.log(`Resultado: ${res}`)
} catch (error) {
    console.log(error.message)
} finally {
     console.log('Chegou no finally')
}

console.log('Conitua')